version: '3.8'

services:
  postgres:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: sleepbot
    ports:
      - "5432:5432"


  sleepbot:
    build:
      context: .
      dockerfile: dockerfile
    env_file: .env
    ports:
      - "8007:8007"